  /// \file GeometryBuilder.h
/*
 *
 * GeometryBuilder.h header template automatically generated by a class generator
 * Creation date : sam. avr. 7 2018
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright 
 */


#ifndef GEOMETRYBUILDER_H
#define GEOMETRYBUILDER_H

// -- root headers
#include <TGeoManager.h>

// -- dqm4hep headers
#include <dqm4hep/StatusCodes.h>
#include <dqm4hep/tinyxml.h>

namespace dqm4hep {
  
  namespace display {

    /** 
     *  @brief  GeometryBuilder class
     */ 
    class GeometryBuilder {
     public:
     /**
      *  @brief  Destructor 
      */
     virtual ~GeometryBuilder();
     
     /**
      *  @brief  Read settings from XML handle
      *  
      *  @param  handle the xml handle
      */
     virtual core::StatusCode readSettings(const core::TiXmlHandle &handle) = 0;
     
     /**
      *  @brief  Build geometry
      */
     virtual TGeoManager* buildGeometry() = 0;
    };
    
    inline GeometryBuilder::~GeometryBuilder() {
      
    }
    
  }

} 

#endif  //  GEOMETRYBUILDER_H
